FROM python:3.10-bullseye

WORKDIR /app

# O PySpark requer o Java instalado (JRE)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-jre \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME="/usr/lib/jvm/default-java"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Esse contêiner vai executar especificamente o script PySpark
CMD ["python", "transform_pyspark.py"]
